name: Machine Learning Workflow CI Advance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil source code dari repository GitHub
    - name: Checkout repository code
      uses: actions/checkout@v3

    # 2. Pasang Python versi 3.12 di server GitHub
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install semua library yang dibutuhkan
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 scikit-learn pandas numpy

    # 4. TAHAP BASIC: Jalankan training menggunakan mekanisme MLflow Project (Bukan python modelling.py)
    - name: Run MLflow Project Retraining
      run: |
        mlflow run MLProject --env-manager=local

    # 5. TAHAP SKILLED: Simpan dan Upload artefak hasil training ke GitHub Artifacts (Biar lulus level Skilled)
    - name: Upload Artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: hasil-model-tanah-aliya
        path: mlruns/

    # 6. Login otomatis ke Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 7. TAHAP ADVANCED: Build Docker Image memanfaatkan fungsi bawaan MLflow
    - name: Build MLflow Docker Image
      run: |
        mlflow models build-docker -m "MLProject/mlruns/1/" -n "aliyapradnya/crop_recommendation_model:latest" --enable-mlserver

    # 8. TAHAP ADVANCED: Push ke Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker push aliyapradnya/crop_recommendation_model:latest