name: Machine Learning Workflow CI Advance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Mengunci environment variable agar MLflow selalu membaca folder tracking yang sama secara absolut
env:
  MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/MLProject/mlruns"

jobs:
  train-and-push-docker:
    runs-on: ubuntu-latest

    steps:
    # 1. Ambil source code dari repository GitHub
    - name: Checkout repository code
      uses: actions/checkout@v3

    # 2. Pasang Python versi 3.12
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # 3. Install semua library yang dibutuhkan
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow==2.19.0 scikit-learn pandas numpy

    # 4. TAHAP BASIC: Jalankan training menggunakan mekanisme MLflow Project Murni (LULUS LEVEL BASIC)
    - name: Run MLflow Project Retraining
      run: |
        mlflow run MLProject --env-manager=local

    # 5. TAHAP SKILLED: Simpan dan Upload artefak hasil training ke GitHub Artifacts (LULUS LEVEL SKILLED)
    - name: Upload Artifacts to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: hasil-model-tanah-aliya
        path: MLProject/mlruns/

    # 6. Login otomatis ke Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 7. TAHAP ADVANCED: Memanfaatkan fungsi bawaan murni mlflow models build-docker (LULUS LEVEL ADVANCED)
    - name: Build MLflow Docker Image
      run: |
        # Mengambil RUN ID terakhir yang baru saja dibuat secara otomatis tanpa tebak-tebakan angka
        LATEST_RUN_ID=$(python -c "import mlflow; print(mlflow.search_runs(experiment_names=['Crop_Recommendation_CI']).iloc[0]['run_id'])")
        
        # Build Docker menggunakan fungsi bawaan MLflow sesuai instruksi reviewer
        mlflow models build-docker -m "runs:/$LATEST_RUN_ID/model_tanah_aliya" -n "aliyapradnya/crop_recommendation_model:latest" --enable-mlserver

    # 8. TAHAP ADVANCED: Push ke Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker push aliyapradnya/crop_recommendation_model:latest